server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hieu
    url: "jdbc:mysql://localhost:3306/reading"
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: '1KB'
      max-file-size: '10MB'
      max-request-size: '10MB'

cors:
  allowedOrigins: '*'


reading:
  app:
    jwtSecret: 'readingSecretKey'
    jwtExpirationMs: '86400000'


